[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.mp4"
    [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"
    Accept-Ranges = "bytes"
