services:
  - type: web
    name: portfolio-video
    env: static
    buildCommand: echo "Static site, no build required"
    publishDir: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
